using Microsoft.OpenApi.Models;
using MyMoola.API.Attributes;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace MyMoola.API.Filters;

public sealed class IdempotencyHeaderOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        var hasIdempotencyAttribute = context.MethodInfo
            .GetCustomAttributes(true)
            .OfType<IdempotencyAttribute>()
            .Any();

        if (!hasIdempotencyAttribute)
            return;

        operation.Parameters ??= new List<OpenApiParameter>();

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = "Idempotency-Key",
            In = ParameterLocation.Header,
            Required = true,
            Schema = new OpenApiSchema { Type = "string" },
            Description = "Unique key to ensure idempotency. Use a UUID generated by the client."
        });
    }
}