// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMoola.Infrastructure.Persistence;

#nullable disable

namespace MyMoola.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505151019_AddRefreshTokens2")]
    partial class AddRefreshTokens2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyMoola.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterState")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("before_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("target_entity");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.DepositAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("DerivationPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("derivation_path");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("deposit_addresses", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("BuyRateKes")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("buy_rate_kes");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fetched_at");

                    b.Property<decimal>("RateKes")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("rate_kes");

                    b.Property<decimal>("RateUsd")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("rate_usd");

                    b.Property<decimal>("SellRateKes")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("sell_rate_kes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("source");

                    b.Property<decimal>("SpreadPercent")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("spread_percent");

                    b.HasKey("Id");

                    b.HasIndex("Currency");

                    b.HasIndex("FetchedAt");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(28,18)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(28,18)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(28,18)")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_ledger_entries_amount", "[amount] > 0");
                        });
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.MpesaTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountKes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_kes");

                    b.Property<string>("CheckoutRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("checkout_request_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("direction");

                    b.Property<string>("MerchantRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("merchant_request_id");

                    b.Property<string>("MpesaReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mpesa_receipt_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RawCallbackPayload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_callback_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutRequestId")
                        .HasFilter("[checkout_request_id] IS NOT NULL");

                    b.HasIndex("MpesaReceiptNumber")
                        .IsUnique()
                        .HasFilter("[mpesa_receipt_number] IS NOT NULL");

                    b.HasIndex("TransactionId");

                    b.ToTable("mpesa_transactions", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.SystemControl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ControlKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("control_key");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("DisabledBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("disabled_by");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ControlKey")
                        .IsUnique();

                    b.ToTable("system_controls", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_note");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(28,18)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CounterpartyUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("counterparty_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("ExchangeRateSnapshot")
                        .HasColumnType("decimal(28,8)")
                        .HasColumnName("exchange_rate_snapshot");

                    b.Property<decimal>("FeeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(28,18)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fee_amount");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("InitiatorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("initiator_user_id");

                    b.Property<decimal?>("KesAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("kes_amount");

                    b.Property<decimal?>("MarketRateSnapshot")
                        .HasColumnType("decimal(28,8)")
                        .HasColumnName("market_rate_snapshot");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("MpesaReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mpesa_reference");

                    b.Property<int>("OnChainConfirmations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("on_chain_confirmations");

                    b.Property<string>("OnChainTxHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("on_chain_tx_hash");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("reference_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MpesaReference")
                        .HasFilter("[mpesa_reference] IS NOT NULL");

                    b.HasIndex("OnChainTxHash")
                        .HasFilter("[on_chain_tx_hash] IS NOT NULL");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.TreasuryPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(28,18)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<bool>("BuyHalted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("buy_halted");

                    b.Property<decimal>("CoverageRatio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("coverage_ratio");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<decimal>("KesReserve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("kes_reserve");

                    b.Property<DateTimeOffset?>("LastRebalancedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_rebalanced_at");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Currency")
                        .IsUnique();

                    b.ToTable("treasury_positions", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("account_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedPinAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_pin_attempts");

                    b.Property<string>("FreezeReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("freeze_reason");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("kyc_status");

                    b.Property<DateTimeOffset?>("KycVerifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("kyc_verified_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_login_at");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("national_id");

                    b.Property<string>("PhoneNumberValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("phone_verified_at");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTimeOffset?>("PinLockedUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("pin_locked_until");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasFilter("[national_id] IS NOT NULL");

                    b.HasIndex("PhoneNumberValue")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(28,18)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<decimal>("LockedBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(28,18)")
                        .HasDefaultValue(0m)
                        .HasColumnName("locked_balance");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Currency")
                        .IsUnique();

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_wallets_balance", "[balance] >= 0");

                            t.HasCheckConstraint("CK_wallets_locked_balance", "[locked_balance] >= 0");
                        });
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.DepositAddress", b =>
                {
                    b.HasOne("MyMoola.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("MyMoola.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMoola.Domain.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.MpesaTransaction", b =>
                {
                    b.HasOne("MyMoola.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MyMoola.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoola.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("MyMoola.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
